program Compras;

uses
  Forms,
  uFrmPrincipal in 'uFrmPrincipal.pas' {frmPrincipal},
  uFrmPadraoRel in '..\padrao\uFrmPadraoRel.pas' {FrmPadraoRel},
  uFrmPesCnpj in '..\Padrao\uFrmPesCnpj.pas',
  uFrmCadComprador in 'uFrmCadComprador.pas' {frmCadComprador},
  uRecError in '..\padrao\uRecError.pas' {ReconcileErrorForm},
  uFuncao in '..\Padrao\uFuncao.pas',
  uFrmCadPadraoEmpCont in '..\Padrao\uFrmCadPadraoEmpCont.pas' {FrmCadPadraoEmpCont},
  uFrmPadraoPesqEmpContabil in '..\Padrao\uFrmPadraoPesqEmpContabil.pas' {FrmPadraoPesqEmpContabil},
  uFrmPesContaCliente in '..\Financas\uFrmPesContaCliente.pas' {FrmPesContaCliente},
  uFrmCadPlanoConta in '..\Contabil\uFrmCadPlanoConta.pas' {frmCadPlanoConta},
  uFrmPesEmpFiscal in '..\Padrao\uFrmPesEmpFiscal.pas' {FrmPesEmpFiscal},
  uFrmPesEmpContabil in '..\Padrao\uFrmPesEmpContabil.pas' {FrmPesEmpContabil},
  uFrmSelEmpresas in '..\Padrao\uFrmSelEmpresas.pas' {FrmSelEmpresas},
  uDmPadrao in '..\Padrao\uDmPadrao.pas' {dmPadrao: TDataModule},
  uDmFind in '..\Padrao\uDmFind.pas' {dmFind: TDataModule},
  uFrmBackup in '..\Padrao\uFrmBackup.pas' {frmBackup},
  uFrmCadCotacao in 'uFrmCadCotacao.pas' {FrmCadCotacao},
  uFrmCadPadrao in '..\padrao\uFrmCadPadrao.pas' {FrmCadPadrao},
  uFrmPadrao in '..\padrao\uFrmPadrao.pas' {FrmPadrao},
  uFrmCadProduto in '..\Produtos\uFrmCadProduto.pas' {FrmCadProduto},
  uFrmCadBem in '..\Patrimonial\uFrmCadBem.pas' {FrmCadBem},
  uFrmCadPadraoEmpFiscal in '..\Padrao\uFrmCadPadraoEmpFiscal.pas' {FrmCadPadraoEmpFiscal},
  uCadConfigCompras in 'uCadConfigCompras.pas' {frmCadConfigCompras},
  uFrmCadPadraoGrid in '..\padrao\uFrmCadPadraoGrid.pas' {FrmCadPadraoGrid},
  uFrmPadraoPesqEmpFiscal in '..\Padrao\uFrmPadraoPesqEmpFiscal.pas' {FrmPadraoPesqEmpFiscal},
  uFrmGerenciaRequisicao in 'uFrmGerenciaRequisicao.pas' {FrmGerenciaRequisicao},
  uFrmPadraoPesquisa in '..\padrao\uFrmPadraoPesquisa.pas' {FrmPadraoPesquisa},
  uFrmSobre in '..\Padrao\uFrmSobre.pas' {FrmSobre},
  uFrmCadCondicaoPgto in 'uFrmCadCondicaoPgto.pas' {FrmCadCondicaoPgto},
  uCadDocSerie in '..\Financas\uCadDocSerie.pas' {frmCadDocSerie},
  uFrmNFE in '..\Fiscal\uFrmNFE.pas' {FrmNfE},
  uFrmGeraCotacao in 'uFrmGeraCotacao.pas' {FrmGeraCotacao},
  uCadCidade in '..\Cadastros\uCadCidade.pas' {frmCadCidade},
  uCadGeral in '..\Cadastros\uCadGeral.pas' {frmCadGeral},
  uFrmPesProdutoGrupo in '..\Padrao\uFrmPesProdutoGrupo.pas' {FrmPesProdutoGrupo},
  uFrmPesNotas in '..\Fiscal\uFrmPesNotas.pas' {frmPesNotas},
  uFrmNotaFiscal in '..\Fiscal\uFrmNotaFiscal.pas' {FrmNotaFiscal},
  uFrmConfigNF in '..\Fiscal\uFrmConfigNF.pas' {FrmConfigNF},
  uFrmCadInventario in 'uFrmCadInventario.pas' {FrmCadInventario},
  uCadCriterioCompra in 'uCadCriterioCompra.pas' {frmCadCriterioCompra},
  uFrmPesClienteFiscal in '..\Padrao\uFrmPesClienteFiscal.pas' {FrmPesClienteFiscal},
  uFrmPesCotacao in 'uFrmPesCotacao.pas' {FrmPesCotacao},
  uFrmCadRequisicao in 'uFrmCadRequisicao.pas' {FrmCadRequisicao},
  uFrmPesMovEstoque in '..\Produtos\uFrmPesMovEstoque.pas' {FrmPesMovEstoque},
  uFrmPesRequisicao in 'uFrmPesRequisicao.pas' {FrmPesRequisicao},
  uFrmRelRequisicao in 'uFrmRelRequisicao.pas' {FrmRelRequisicao},
  uFrmRelCotacao in 'uFrmRelCotacao.pas' {FrmRelCotacao},
  uFrmCadPedidoCompra in 'uFrmCadPedidoCompra.pas' {FrmCadPedidoCompra},
  uFrmPadraoRelEmpresa in '..\Padrao\uFrmPadraoRelEmpresa.pas' {FrmPadraoRelEmpresa},
  uFrmPadraoRelEmpFiscal in '..\Padrao\uFrmPadraoRelEmpFiscal.pas' {FrmPadraoRelEmpFiscal},
  uFrmRelContagem in '..\Fiscal\uFrmRelContagem.pas' {FrmRelContagem},
  uFrmCadProdDeposito in '..\Produtos\uFrmCadProdDeposito.pas' {FrmCadProdDeposito},
  uFrmPesConferencia in 'uFrmPesConferencia.pas' {FrmPesConferencia},
  uFrmPesProduto in '..\Padrao\uFrmPesProduto.pas' {FrmPesProduto},
  uFrmMovEstoque in '..\Produtos\uFrmMovEstoque.pas' {FrmMovEstoque},
  uFrmRelProdEstoque in '..\Fiscal\uFrmRelProdEstoque.pas' {FrmRelProdEstoque},
  uFrmRelEstoque in '..\Fiscal\uFrmRelEstoque.pas' {FrmRelEstoque},
  uCadFabricante in 'uCadFabricante.pas' {frmCadFabricante},
  uFrmPesRecepcaoNFE in 'uFrmPesRecepcaoNFE.pas' {FrmPesRecepcaoNFE},
  uFrmPesPedidoCompra in 'uFrmPesPedidoCompra.pas' {FrmPesPedidoCompra},
  uFrmHistoricoRecepcao in 'uFrmHistoricoRecepcao.pas' {FrmHistoricoRecepcao},
  uFrmPesRecepcao in 'uFrmPesRecepcao.pas' {FrmPesRecepcao},
  uFrmRelCotacaoValor in 'uFrmRelCotacaoValor.pas' {FrmRelCotacaoValor},
  uFrmRelConfPedidoCompra in 'uFrmRelConfPedidoCompra.pas' {FrmRelConfPedidoCompra},
  uFrmRelPedidoCompra in 'uFrmRelPedidoCompra.pas' {FrmRelPedidoCompra},
  uCadIndice in '..\Financas\uCadIndice.pas' {frmCadIndice},
  uFrmCotacaoFilial in 'uFrmCotacaoFilial.pas' {FrmCotacaoFilial},
  uFrmDistribuiNF in 'uFrmDistribuiNF.pas' {FrmDistribuiNF},
  uFrmSelNfE in 'uFrmSelNfE.pas' {FrmSelNfE},
  uFrmPesInventario in 'uFrmPesInventario.pas' {FrmPesInventario};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Nilus - Compras';
  Application.CreateForm(TdmPadrao, dmPadrao);
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.CreateForm(TdmFind, dmFind);
  Application.Run;
end.
