program Financas;

uses
  Forms,
  uFrmPadrao in '..\padrao\uFrmPadrao.pas' {FrmPadrao},
  uFrmCadPadrao in '..\padrao\uFrmCadPadrao.pas' {FrmCadPadrao},
  uFrmCadPadraoEmpCont in '..\padrao\uFrmCadPadraoEmpCont.pas' {FrmCadPadraoEmpCont},
  uFrmCadPadraoGrid in '..\padrao\uFrmCadPadraoGrid.pas' {FrmCadPadraoGrid},
  uFuncao in '..\padrao\uFuncao.pas',
  uFrmPadraoRel in '..\padrao\uFrmPadraoRel.pas' {FrmPadraoRel},
  uDmPadrao in '..\Padrao\uDmPadrao.pas' {dmPadrao: TDataModule},
  uFrmCadConta in 'uFrmCadConta.pas' {frmCadConta},
  uCadMovFinanceira in 'uCadMovFinanceira.pas' {frmCadMovFinanceira},
  uCadPrevisaoPag in 'uCadPrevisaoPag.pas' {FrmCadPrevisaoPag},
  uFrmPrincipal in 'uFrmPrincipal.pas' {frmPrincipal},
  uFrmCadPadraoEmpFiscal in '..\padrao\uFrmCadPadraoEmpFiscal.pas' {FrmCadPadraoEmpFiscal},
  uFrmPadraoPesquisa in '..\padrao\uFrmPadraoPesquisa.pas' {FrmPadraoPesquisa},
  uFrmPesEmpContabil in '..\Padrao\uFrmPesEmpContabil.pas' {FrmPesEmpContabil},
  uFrmPesEmpFiscal in '..\Padrao\uFrmPesEmpFiscal.pas' {FrmPesEmpFiscal},
  uFrmPadraoPesqEmpContabil in '..\padrao\uFrmPadraoPesqEmpContabil.pas' {FrmPadraoPesqEmpContabil},
  uFrmPadraoPesqEmpFiscal in '..\padrao\uFrmPadraoPesqEmpFiscal.pas' {FrmPadraoPesqEmpFiscal},
  uFrmPesPrevisaoPag in 'uFrmPesPrevisaoPag.pas' {FrmPesPrevisaoPag},
  uCadGeral in '..\Cadastros\uCadGeral.pas' {frmCadGeral},
  uCadCidade in '..\Cadastros\uCadCidade.pas' {frmCadCidade},
  uRecError in '..\padrao\uRecError.pas' {ReconcileErrorForm},
  uCadDocSerie in 'uCadDocSerie.pas' {frmCadDocSerie},
  uFrmCadProduto in '..\Produtos\uFrmCadProduto.pas' {FrmCadProduto},
  uFrmCadSafra in '..\Cadastros\uFrmCadSafra.pas' {FrmCadSafra},
  uFrmCadCaixa in 'uFrmCadCaixa.pas' {FrmCadCaixa},
  uFrmCadRateio in 'uFrmCadRateio.pas' {FrmCadRateio},
  uFrmCadRateioTalhao in 'uFrmCadRateioTalhao.pas' {FrmCadRateioTalhao},
  uFrmCadConfigFinanc in 'uFrmCadConfigFinanc.pas' {FrmCadConfigFinanc},
  uFrmAlteraPortador in 'uFrmAlteraPortador.pas' {FrmAlteraPortador},
  uCadTituloPag in 'uCadTituloPag.pas' {FrmCadTituloPag},
  uFrmCadMovConta in 'uFrmCadMovConta.pas' {FrmCadMovConta},
  uFrmPesTitulos in 'uFrmPesTitulos.pas' {FrmPesTitulos},
  uCadPrevisaoRec in 'uCadPrevisaoRec.pas' {FrmCadPrevisaoRec},
  uFrmPesPrevisaoRec in 'uFrmPesPrevisaoRec.pas' {FrmPesPrevisaoRec},
  uFrmPesTituloRec in 'uFrmPesTituloRec.pas' {FrmPesTituloRec},
  uFrmCadMovTransf in 'uFrmCadMovTransf.pas' {FrmCadMovTransf},
  uCadTituloRec in 'uCadTituloRec.pas' {FrmCadTituloRec},
  uCadBanco in 'uCadBanco.pas' {frmCadBanco},
  uCadIndice in 'uCadIndice.pas' {frmCadIndice},
  uFrmCadMovCaixa in 'uFrmCadMovCaixa.pas' {FrmCadMovCaixa},
  uFrmPagTitulo in 'uFrmPagTitulo.pas' {FrmPagTitulo},
  uFrmPesCnpj in '..\Padrao\uFrmPesCnpj.pas' {FrmPesCnpj},
  uFrmCadUsuario in '..\Cadastros\uFrmCadUsuario.pas' {frmCadUsuario},
  uFrmRecTitulo in 'uFrmRecTitulo.pas' {FrmRecTitulo},
  uFrmCadBem in '..\Patrimonial\uFrmCadBem.pas' {FrmCadBem},
  uFrmPesTituloPag in 'uFrmPesTituloPag.pas' {FrmPesTituloPag},
  uFrmRelMovCaixa in 'uFrmRelMovCaixa.pas' {FrmRelMovCaixa},
  uFrmRelExtratoConta in 'uFrmRelExtratoConta.pas' {FrmRelExtratoConta},
  uCadResultado in 'uCadResultado.pas' {FrmCadResultado},
  uFrmCadChequeAvulso in 'uFrmCadChequeAvulso.pas' {FrmCadChequeAvulso},
  uFrmRelGerencial in 'uFrmRelGerencial.pas' {FrmRelGerencial},
  uFrmRelResultado in 'uFrmRelResultado.pas' {frmRelResultado},
  uFrmRelRateio in 'uFrmRelRateio.pas' {frmRelRateio},
  uFrmRelFichaGerencial in 'uFrmRelFichaGerencial.pas' {FrmRelFichaGerencial},
  uFrmCadGerencial in 'uFrmCadGerencial.pas' {FrmCadGerencial},
  uFrmRelConfResultados in 'uFrmRelConfResultados.pas' {FrmRelConfResultado},
  uFrmRelFluxoCaixa in 'uFrmRelFluxoCaixa.pas' {FrmRelFluxoCaixa},
  uFrmAlteraPag in 'uFrmAlteraPag.pas' {frmAlteraPag},
  uFrmAlteraRec in 'uFrmAlteraRec.pas' {frmAlteraRec},
  uFrmRelMovimentacao in 'uFrmRelMovimentacao.pas' {FrmRelMovimentacao},
  uFrmSobre in '..\padrao\uFrmSobre.pas' {FrmSobre},
  uFrmRelContasReceber in 'uFrmRelContasReceber.pas' {FrmRelContasReceber},
  uFrmRelExtratoCaixa in 'uFrmRelExtratoCaixa.pas' {FrmRelExtratoCaixa},
  uFrmPadraoPesquisaDevExpress in '..\Padrao\uFrmPadraoPesquisaDevExpress.pas' {FrmPadraoPesquisaDevExpress},
  uFrmPesGerencial in 'uFrmPesGerencial.pas' {FrmPesGerencial},
  uFrmPesMovTransf in 'uFrmPesMovTransf.pas' {FrmPesqMovTransf},
  uFrmBackup in '..\padrao\uFrmBackup.pas' {frmBackup},
  uFrmRelFluxoCaixaMensal in 'uFrmRelFluxoCaixaMensal.pas' {FrmRelFluxoCaixaMensal},
  uFrmRelExtratoFornecedor in 'uFrmRelExtratoFornecedor.pas' {FrmRelExtratoFornecedor},
  uFrmRelExtratoCliente in 'uFrmRelExtratoCliente.pas' {FrmRelExtratoCliente},
  uFrmCadTalhao in 'uFrmCadTalhao.pas' {FrmCadTalhao},
  uFrmPesContaCliente in 'uFrmPesContaCliente.pas' {FrmPesContaCliente},
  uFrmCadPlanoConta in '..\Contabil\uFrmCadPlanoConta.pas' {frmCadPlanoConta},
  uFrmSelEmpresas in '..\Padrao\uFrmSelEmpresas.pas' {FrmSelEmpresas},
  uDmFind in '..\Padrao\uDmFind.pas' {dmFind: TDataModule},
  uFrmPadraoRelEmpresa in '..\Padrao\uFrmPadraoRelEmpresa.pas' {FrmPadraoRelEmpresa},
  uFrmCadCultura in '..\Armazem\uFrmCadCultura.pas' {FrmCadCultura},
  uFrmCadGrupoGerencial in 'uFrmCadGrupoGerencial.pas' {FrmCadGrupoGerencial},
  uFrmCadSegmento in '..\Cadastros\uFrmCadSegmento.pas' {FrmCadSegmento},
  uFrmPesCompensacao in 'uFrmPesCompensacao.pas' {FrmPesCompensacao},
  uFrmRelContasPagar in 'uFrmRelContasPagar.pas' {FrmRelContasPagar},
  uFrmRelContasPagarPortador in 'uFrmRelContasPagarPortador.pas' {FrmRelContasPagarPortador},
  uFrmRelExtratoBancario in 'uFrmRelExtratoBancario.pas' {FrmRelExtratoBancario},
  uFrmPesProduto in '..\Padrao\uFrmPesProduto.pas' {FrmPesProduto},
  uFrmAutorizacao in '..\Padrao\uFrmAutorizacao.pas' {FrmAutorizacao},
  uFrmProcessa in '..\Padrao\uFrmProcessa.pas' {FrmProcessa},
  uFrmCadGrupoCad in '..\Cadastros\uFrmCadGrupoCad.pas' {FrmCadGrupoCad};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Nilus - Financas';
  Application.HelpFile := '';
  Application.CreateForm(TdmPadrao, dmPadrao);
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.CreateForm(TdmFind, dmFind);
  Application.Run;
end.
